### ISSUE TITLE
Uncaught runtime error: Canceled: Canceled 

### ISSUE THREAD

**Issue by jpdery** [CodinGame/monaco-editor-react#50]
I'm working on a tabbed editor that switches files using the `fileUri` prop. However, when I switch files a bit too fast, I'm getting this error.

Is there a way to catch this error ?

<img width="809" alt="image" src="https://github.com/CodinGame/monaco-editor-react/assets/572660/8b94fe1e-4325-456c-86ac-819b183bef7d">

Thanks

**Comment by CGNonofr** [comment]
Unfortunately, it's in VSCode itself:

https://github.com/microsoft/vscode/blob/fae9ee17dd825c1a94811e781d7511029a3e511d/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L563

`autoDetectLanguage` returns a promise that is rejected if the model is disposed before the delayer expire (600ms)

Feel free to open a PR/issue on the VSCode side :)

Is it blocking for you?

**Comment by jpdery** [comment]
Thanks again!

It's not blocking, just mildly annoying.

:)
